spring.application.name=grammitra-backend
spring.data.mongodb.uri=mongodb+srv://sharmamia173_db_user:n4p7RpWZSwMxFnWj@m0.4wxzhj8.mongodb.net/grammitra?retryWrites=true&w=majority

spring.data.mongodb.database=grammitra
server.port=8080



